export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',

  // Tenant
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SLUG_TAKEN: 'TENANT_SLUG_TAKEN',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_LIMIT_EXCEEDED: 'TENANT_LIMIT_EXCEEDED',

  // Worker
  WORKER_NOT_FOUND: 'WORKER_NOT_FOUND',
  WORKER_ALREADY_EXISTS: 'WORKER_ALREADY_EXISTS',
  WORKER_INACTIVE: 'WORKER_INACTIVE',
  WORKER_NFC_CARD_TAKEN: 'WORKER_NFC_CARD_TAKEN',

  // Attendance
  ATTENDANCE_DUPLICATE: 'ATTENDANCE_DUPLICATE',
  ATTENDANCE_NOT_FOUND: 'ATTENDANCE_NOT_FOUND',
  ATTENDANCE_ALREADY_CLOCKED_OUT: 'ATTENDANCE_ALREADY_CLOCKED_OUT',
  ATTENDANCE_NO_OPEN_RECORD: 'ATTENDANCE_NO_OPEN_RECORD',

  // Leave
  LEAVE_INSUFFICIENT_BALANCE: 'LEAVE_INSUFFICIENT_BALANCE',
  LEAVE_REQUEST_NOT_FOUND: 'LEAVE_REQUEST_NOT_FOUND',
  LEAVE_REQUEST_NOT_PENDING: 'LEAVE_REQUEST_NOT_PENDING',
  LEAVE_OVERLAPPING: 'LEAVE_OVERLAPPING',
  LEAVE_TYPE_NOT_FOUND: 'LEAVE_TYPE_NOT_FOUND',

  // Payroll
  PAYROLL_PERIOD_NOT_FOUND: 'PAYROLL_PERIOD_NOT_FOUND',
  PAYROLL_ALREADY_GENERATED: 'PAYROLL_ALREADY_GENERATED',
  PAYSLIP_NOT_FOUND: 'PAYSLIP_NOT_FOUND',

  // Kiosk
  KIOSK_NOT_FOUND: 'KIOSK_NOT_FOUND',
  KIOSK_NOT_ACTIVE: 'KIOSK_NOT_ACTIVE',
  KIOSK_SERIAL_TAKEN: 'KIOSK_SERIAL_TAKEN',
  KIOSK_SYNC_FAILED: 'KIOSK_SYNC_FAILED',
  KIOSK_TOKEN_INVALID: 'KIOSK_TOKEN_INVALID',

  // Shift
  SHIFT_NOT_FOUND: 'SHIFT_NOT_FOUND',
  SHIFT_ASSIGNMENT_CONFLICT: 'SHIFT_ASSIGNMENT_CONFLICT',

  // Emergency
  INCIDENT_NOT_FOUND: 'INCIDENT_NOT_FOUND',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
