import { UserRole } from '../types/roles.enum';

export enum Permission {
  ATTENDANCE_READ_OWN = 'attendance:read:own',
  ATTENDANCE_READ_FACTORY = 'attendance:read:factory',
  ATTENDANCE_CORRECT_FACTORY = 'attendance:correct:factory',
  PAYROLL_VIEW_OWN = 'payroll:view:own',
  PAYROLL_GENERATE_FACTORY = 'payroll:generate:factory',
  SHIFT_ASSIGN_FACTORY = 'shift:assign:factory',
  SHIFT_VIEW = 'shift:view',
  LEAVE_APPROVE_DEPARTMENT = 'leave:approve:department',
  LEAVE_REQUEST_OWN = 'leave:request:own',
  EMERGENCY_TRIGGER_FACTORY = 'emergency:trigger:factory',
  EMERGENCY_VIEW = 'emergency:view',
  WORKER_MANAGE_FACTORY = 'worker:manage:factory',
  WORKER_VIEW_FACTORY = 'worker:view:factory',
  TENANT_MANAGE_GLOBAL = 'tenant:manage:global',
  KIOSK_MANAGE_FACTORY = 'kiosk:manage:factory',
  REPORT_VIEW_FACTORY = 'report:view:factory',
  COMPLIANCE_VIEW = 'compliance:view',
  ANALYTICS_VIEW = 'analytics:view',
}

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.WORKER]: [
    Permission.ATTENDANCE_READ_OWN,
    Permission.PAYROLL_VIEW_OWN,
    Permission.LEAVE_REQUEST_OWN,
    Permission.SHIFT_VIEW,
  ],
  [UserRole.SUPERVISOR]: [
    Permission.ATTENDANCE_READ_OWN,
    Permission.ATTENDANCE_READ_FACTORY,
    Permission.PAYROLL_VIEW_OWN,
    Permission.LEAVE_REQUEST_OWN,
    Permission.LEAVE_APPROVE_DEPARTMENT,
    Permission.SHIFT_VIEW,
    Permission.SHIFT_ASSIGN_FACTORY,
    Permission.WORKER_VIEW_FACTORY,
    Permission.EMERGENCY_VIEW,
    Permission.REPORT_VIEW_FACTORY,
    Permission.ANALYTICS_VIEW,
  ],
  [UserRole.ADMIN]: [
    Permission.ATTENDANCE_READ_OWN,
    Permission.ATTENDANCE_READ_FACTORY,
    Permission.ATTENDANCE_CORRECT_FACTORY,
    Permission.PAYROLL_VIEW_OWN,
    Permission.PAYROLL_GENERATE_FACTORY,
    Permission.LEAVE_REQUEST_OWN,
    Permission.LEAVE_APPROVE_DEPARTMENT,
    Permission.SHIFT_VIEW,
    Permission.SHIFT_ASSIGN_FACTORY,
    Permission.WORKER_VIEW_FACTORY,
    Permission.WORKER_MANAGE_FACTORY,
    Permission.EMERGENCY_VIEW,
    Permission.EMERGENCY_TRIGGER_FACTORY,
    Permission.KIOSK_MANAGE_FACTORY,
    Permission.REPORT_VIEW_FACTORY,
    Permission.ANALYTICS_VIEW,
    Permission.COMPLIANCE_VIEW,
  ],
  [UserRole.OWNER]: [
    Permission.ATTENDANCE_READ_OWN,
    Permission.ATTENDANCE_READ_FACTORY,
    Permission.ATTENDANCE_CORRECT_FACTORY,
    Permission.PAYROLL_VIEW_OWN,
    Permission.PAYROLL_GENERATE_FACTORY,
    Permission.LEAVE_REQUEST_OWN,
    Permission.LEAVE_APPROVE_DEPARTMENT,
    Permission.SHIFT_VIEW,
    Permission.SHIFT_ASSIGN_FACTORY,
    Permission.WORKER_VIEW_FACTORY,
    Permission.WORKER_MANAGE_FACTORY,
    Permission.EMERGENCY_VIEW,
    Permission.EMERGENCY_TRIGGER_FACTORY,
    Permission.KIOSK_MANAGE_FACTORY,
    Permission.REPORT_VIEW_FACTORY,
    Permission.ANALYTICS_VIEW,
    Permission.COMPLIANCE_VIEW,
  ],
  [UserRole.SAAS_ADMIN]: [
    Permission.TENANT_MANAGE_GLOBAL,
    Permission.ATTENDANCE_READ_FACTORY,
    Permission.ATTENDANCE_CORRECT_FACTORY,
    Permission.PAYROLL_GENERATE_FACTORY,
    Permission.LEAVE_APPROVE_DEPARTMENT,
    Permission.SHIFT_ASSIGN_FACTORY,
    Permission.WORKER_MANAGE_FACTORY,
    Permission.EMERGENCY_TRIGGER_FACTORY,
    Permission.KIOSK_MANAGE_FACTORY,
    Permission.REPORT_VIEW_FACTORY,
    Permission.ANALYTICS_VIEW,
    Permission.COMPLIANCE_VIEW,
  ],
  [UserRole.KIOSK_DEVICE]: [],
};

export const PERMISSIONS_KEY = 'permissions';
export const ROLES_KEY = 'roles';
export const IS_PUBLIC_KEY = 'isPublic';
